version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"